import Head from './layouts/head';
import Loader from './layouts/loader';
import Header from './layouts/header';
import Script from './layouts/script';
import Footer from './layouts/footer';
import ScrollTop from './layouts/scroll-top';
import NextTopLoader from 'nextjs-toploader';


const apiUrl = 'https://school.web.astrosoftware.com.np/api/v1/'
const apiKey = 'p2yrhocea##)+87ob2#=$8&hs+@yh0dtr^nxeoq$tjug%se4fl'
const samanyaGyanUrl = 'samanya-gyan'
const loksewaUrl = 'categories'

export const metadata = {
    title: 'This is Home Page',
    description: 'Generated by create next app',
};

interface Props {
    children: React.ReactNode
}


interface Loksewa {
    id: number,
    title: string,
}

async function getLoksweaData() {

    try {
        const response = await fetch(`${apiUrl}${loksewaUrl}`, {
            headers: {
                'Api-Key': apiKey,
            },
        });

        if (!response.ok) {
            throw new Error(`HTTP error! Status: ${response.status}`);
        }
        return await response.json();

    } catch (error: any) {
        console.error('Error fetching Loksewa:', error.message);
        throw error;
    }
}

interface SamanyaGyan {
    id: number,
    title: string,
    language: string,
    count: number,
    nepalId: number,
    globalId: number,
}

async function getSamanyaGyanData() {
    try {
        const response = await fetch(`${apiUrl}${samanyaGyanUrl}`, {
            headers: {
                'Api-Key': apiKey,
            },
        });
        if (!response.ok) {
            throw new Error(`HTTP error! Status: ${response.status}`);
        }
        return await response.json();

    } catch (error: any) {
        console.error('Error fetching SamanyaGyan:', error.message);
        throw error;
    }
}


export default async function RootLayout({children}: Props) {
    const samanyaGyanDatas: Array<SamanyaGyan> = await getSamanyaGyanData();
    const LoksewaDatas: Array<Loksewa> = await getLoksweaData();

    return (
        <>
            <html lang="en" className="no-touch">

            <Head/>

            <body className="light-theme">
            <NextTopLoader color="red"/>

            <Header data={{LoksewaDatas, samanyaGyanDatas}}/>

            {children}

            <Footer/>
            <ScrollTop/>
            <Script/>

            </body>
            </html>
        </>
    );
}
