import Head from './layouts/head';
import Loader from './layouts/loader';
import Header from './layouts/header';
import Script from './layouts/script';
import Footer from './layouts/footer';
import ScrollTop from './layouts/scroll-top';
import NextTopLoader from 'nextjs-toploader';
import {getLokSewaData, getSamanyaGyanData, getBlogCategoryData} from './utils/globalApiFetch';


export const metadata = {
    title: 'This is Home Page',
    description: 'Generated by create next app',
};

interface Props {
    children: React.ReactNode
}

export default async function RootLayout({children}: Props) {

    const [samanyaGyanDatas, LoksewaDatas, blogCategories] = await Promise.all([
        getSamanyaGyanData(),
        getLokSewaData(),
        getBlogCategoryData(),
    ]);

    return (
        <>
            <html lang="en" className="no-touch">

            <Head/>

            <body className="light-theme">
            <NextTopLoader color="red"/>

            <Header data={{LoksewaDatas, samanyaGyanDatas, blogCategories}}/>

            {children}

            <Footer/>
            <ScrollTop/>
            <Script/>

            </body>
            </html>
        </>
    );
}
